language: cpp

compiler:
  - gcc

env:
  matrix:
    - PLATFORM=linux DEPLOY_RELEASE=true
    - PLATFORM=linux RUN_COVERALLS=true

before_install:
  - build/travis/to_before_install.sh

install:
  - build/travis/to_install.sh

before_script:
  - build/travis/to_before_script.sh

script:
  - build/travis/to_script.sh

after_success:
  - build/travis/to_after_success.sh

before_deploy:
  - build/travis/before_deploy.sh

deploy:
  provider: releases
  api-key: $GITHUB_TOKEN
  file: "out/potato.$TRAVIS_TAG.$TRAVIS_OS_NAME.tar.gz"
  skip_cleanup: true
  on:
    condition: $DEPLOY_RELEASE = true
    tags: true
    all_branches: true

notifications:
  email:
    - alex@alexchi.me
  on_success: change
  on_failure: always

