platform:
  - x86

configuration:
  - Release

install:
  - cinst install wget
  - cinst install cmake
  - cinst install qt-sdk-windows-x86-msvc2010_opengl
  - cinst install Devbox-UnZip

before_build:
  - mkdir out
  - mkdir out/bin
  - mkdir out/lib
  - cd out
  - wget ftp://sourceware.org/pub/pthreads-win32/pthreads-w32-2-9-1-release.zip
  - unzip pthreads-w32-2-9-1-release.zip

build:
  project: out/make/all.sln

